// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  designSystemSidebar: [{type: 'autogenerated', dirName: 'design-system'}],
  aiAgentsSidebar: [{type: 'autogenerated', dirName: 'developing-with-agents'}],
  apisServicesSidebar: [{type: 'autogenerated', dirName: 'apis-and-services'}],
  deploySidebar: [{type: 'autogenerated', dirName: 'build-and-deploy'}],
  guideSidebar: [{type: 'autogenerated', dirName: 'guide'}],
  studioSidebar: [{type: 'autogenerated', dirName: 'studio'}],
  userInterfacesSidebar: [{type: 'autogenerated', dirName: 'user-interfaces'}],

  // But you can create a sidebar manually one by one
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
