// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  designSystemSidebar: [{type: 'autogenerated', dirName: 'dummy-docs/design-system'}],
  platformSidebar: [{type: 'autogenerated', dirName: 'dummy-docs/platform'}],
  aiAgentsSidebar: [{type: 'autogenerated', dirName: 'dummy-docs/developing_with_agents'}],
  apisServicesSidebar: [{type: 'autogenerated', dirName: 'dummy-docs/apis_and_services'}],
  deploySidebar: [{type: 'autogenerated', dirName: 'dummy-docs/build_and_deploy'}],
  howToSidebar: [{type: 'autogenerated', dirName: 'dummy-docs/how-to'}],
  studioSidebar: [{type: 'autogenerated', dirName: 'dummy-docs/studio'}],
  userInterfacesSidebar: [{type: 'autogenerated', dirName: 'dummy-docs/user_interfaces'}],


  // But you can create a sidebar manually one by one
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
