/** @type {import('@docusaurus/plugin-content-docs').SidebarConfig} */
export default [
  {
    type: 'doc',
    id: 'build-and-deploy/overview',
  },
  {
    type: 'category',
    label: 'build',
    collapsible: true,
    collapsed: true,
    items: [
      {
        type: 'category',
        label: 'web',
        collapsible: true,
        collapsed: true,
        items: [
          {
            type: 'doc',
            id: 'build-and-deploy/build/web/build-options',
          },

          {
            type: 'category',
            label: 'Packaging',
            collapsible: true,
            collapsed: true,
            items: [
              {
                type: 'category',
                label: 'Package WAR',
                collapsible: true,
                collapsed: true,
                items: [
                  {
                    type: 'doc',
                    id: 'build-and-deploy/build/web/package/war/build-war-from-studio',
                  },
                  {
                    type: 'doc',
                    id: 'build-and-deploy/build/web/package/war/build-war-from-projectzip',
                  },
                  {
                    type: 'doc',
                    id: 'build-and-deploy/build/web/package/war/build-war-using-docker',
                  },
                ],
              },

              {
                type: 'category',
                label: 'Docker Image',
                collapsible: true,
                collapsed: true,
                items: [
                  {
                    type: 'doc',
                    id: 'build-and-deploy/build/web/package/docker/docker-image',
                  },
                ],
              },
            ],
          },

          {
            type: 'doc',
            id: 'build-and-deploy/build/web/static-content',
          },
        ],
      },
      {
        type: 'category',
        label: 'mobile',
        collapsible: true,
        collapsed: true,
        items: [
          {
            type: 'doc',
            id: 'build-and-deploy/build/mobile/overview',
          },
        ],
      },
    ],
  },

  /* ================= DEPLOY ================= */
  {
    type: 'category',
    label: 'Deploy',
    collapsible: true,
    collapsed: true,
    items: [
      {
        type: 'doc',
        id: 'build-and-deploy/deploy/one-click deployment',
      },
      {
        type: 'doc',
        id: 'build-and-deploy/deploy/deploy-to-web-server',
      },
      {
        type: 'doc',
        id: 'build-and-deploy/deploy/container-deployment',
      },
      {
        type: 'doc',
        id: 'build-and-deploy/deploy/deploy-static-content',
      },
    ],
  },

  /* ================= PUBLISH ================= */
  {
    type: 'category',
    label: 'Publish',
    collapsible: true,
    collapsed: true,
    items: [
      {
        type: 'doc',
        id: 'build-and-deploy/publish/overview',
      },
    ],
  },

  /* ================= PIPELINE ================= */
  {
    type: 'category',
    label: 'Pipeline',
    collapsible: true,
    collapsed: true,
    items: [
      {
        type: 'doc',
        id: 'build-and-deploy/pipeline/overview',
      },
      {
        type: 'category',
        label: 'Continuous Integration',
        collapsible: true,
        collapsed: true,
        items: [
          {
            type: 'category',
            label: 'VCS Integration',
            collapsible: true,
            collapsed: true,
            items: [
              {
                type: 'autogenerated',
                dirName: 'build-and-deploy/pipeline/continuous-integration/vcs',
              },
            ],
          },
          {
            type: 'category',
            label: 'WaveMaker Internal CI/CD',
            collapsible: true,
            collapsed: true,
            items: [
              {
                type: 'autogenerated',
                dirName: 'build-and-deploy/pipeline/continuous-integration/internal-cicd',
              },
            ],
          },
        ],
      },
      {
        type: 'category',
        label: 'Continuous Deployment',
        collapsible: true,
        collapsed: true,
        items: [
          {
            type: 'autogenerated',
            dirName: 'build-and-deploy/pipeline/continuous-deployment',
          },
        ],
      },
    ],
  },
];
