{
  "default": false,
  "MD003" : true,
  "MD004" : true,
  "MD005" : true,
  "MD007" : false,
  "MD009" : false,
  "MD011" : true,
  "MD012" : false,
  "MD014" : true,
  "MD018" : true,
  "MD019" : true,
  "MD020" : true,
  "MD021" : true,
  "MD022" : false,
  "MD023" : true,
  "MD025" : false,
  "MD026" : false,
  "MD027" : true,
  "MD028" : true,
  "MD031" : false,
  "MD034" : false,
  "MD035" : true,
  "MD039" : true,
  "MD040" : false,
  "MD041" : false,
  "MD042" : false,
  "MD043" : true,
  "MD044" : true,
  "MD045" : false,
  "MD046" : true,
  "MD048" : true
}